services:
  foo:
    image: foo
    restart: no
  bar:
    container_name: foobar
    restart: always
    image: bar
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
    depends_on:
      - bar
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - my_first_volume/data
      - my_second_volume/opt

volumes:
  my_first_volume:
  my_second_volume:
  
networks:
  default:
    name: network_default
